#!/usr/bin/env node

var Converter = require('./lib/csv-to-json.js');

var args = process.argv;

args.shift();
args.shift();

args.push(['University Name', 'City', 'State', 'Postal Code']); //empty select headers
args.push('University Name'); //empty for index
args.push(','); // delimiter

args.length > 2 || process.exit(1);

var converter = Object.create(Converter.prototype);

console.log("converting " + args[0] + " to " + args[1]);

console.log(args);

conv = Converter.apply(converter, args);

converter.convert(function(err){
	if(err){
		console.log("error occured", err);
	} else {
		console.log("file converted succesfully");
	}
	process.exit(1);
});
